version: '3.7'

services:
  backend:
    build:
      context: app/backend 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    depends_on: 
      - db 
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/multistore?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root      
    networks:
      - backend-network
      - frontend-network
  frontend: 
    build:
      context: app/frontend
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    restart: always
    depends_on: 
      - backend
    networks: 
      - frontend-network
  db:
    build:
      context: database 
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    volumes: 
      - db-data:/var/lib/postgres
    networks: 
      - backend-network
volumes:
  db-data:
    
networks:
  backend-network:
  frontend-network: