spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docker?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: docker
    password: docker

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 588236016572-ol2h6djeb1opi79trdajhd2gnr33crh9.apps.googleusercontent.com
            clientSecret: xN895XYM3PE0yiMGOQw6tCd1
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 414586949544756
            clientSecret: 265cb2cd590cf11c24bf8c003ac82593
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  mail:
    host: smtp.gmail.com
    port: 587
    username: EMAIL
    password: PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  auth:
    jwt:
      secret: 926D96C90030DD58429D2751AC1BDBBC
      expiration:
        mili-sec: 864000000

  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
#      - https://localhost:8181/oauth2/callback/google
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
server:
  port: 8181
  ssl:
    key-alias: selfsigned
    key-password: password
    key-store: src/main/resources/tmp_keystore.jks
    key-store-provider: SUN
    key-store-password: password
    key-store-type: JKS