spring:
  datasource:
    mok:
      url: $URL
      username: $USERNAME
      password: $PASSWORD
      driverClassName: org.postgresql.Driver
    mop:
      url: $URL
      username: $USERNAME
      password: $PASSWORD
      driverClassName: org.postgresql.Driver
    moz:
      url: $URL
      username: $USERNAME
      password: $PASSWORD
      driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: $OAUTH2_GOOGLE_CLIENT_ID
            clientSecret: $OAUTH2_GOOGLE_CLIENT_SECRET
            redirectUri: $OAUTH2_GOOGLE_REDIRECT_URI_TO_BACKEND
            scope:
              - email
              - profile
          facebook:
            clientId: $OAUTH2_FACEBOOK_CLIENT_ID
            clientSecret: $OAUTH2_FACEBOOK_CLIENT_SECRET
            redirectUri: $OAUTH2_FACEBOOK_REDIRECT_URI_TO_BACKEND
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  mail:
    host: smtp.gmail.com
    port: 587
    username: $EMAIL_USERNAME
    password: $EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    redirect:
      server:
        uri: $FRONTEND_SERVICE_URL

app:
  signature:
    secret: $SIGNATURE_SECRET
  auth:
    jwt:
      secret: $JWT_SECRET
      expiration:
        mili-sec: 3600000
    forgotPasswordToken:
      expiration:
        mili-sec: 600000

  oauth2:
    authorizedRedirectUris:
      - $OAUTH2_AUTHORIZED_REDIRECT_URIS
logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG